export enum MovieGenre {
  ACTION = "Action",
  ADVENTURE = "Adventure",
  COMEDY = "Comedy",
  DRAMA = "Drama",
  HORROR = "Horror",
  SCIFI = "Science Fiction",
  FANTASY = "Fantasy",
  MYSTERY = "Mystery",
  THRILLER = "Thriller",
  ROMANCE = "Romance",
  CRIME = "Crime",
  WAR = "War",
  WESTERN = "Western",
  MUSICAL = "Musical",
  ANIMATION = "Animation",
  DOCUMENTARY = "Documentary",
  BIOGRAPHY = "Biography",
  FAMILY = "Family",
  HISTORICAL = "Historical",
  SPORTS = "Sports",
}
